#pragma once
#ifndef DAWG_VERSION_H
#define DAWG_VERSION_H

#define DAWG_VERSION_STRING		"2.0.9000"
#define DAWG_PACKAGE_STRING		"dawg 2.0.9000"
#define DAWG_VERSION_INTEGER	2009000
#define DAWG_VERSION_MAJOR		2
#define DAWG_VERSION_MINOR		0
#define DAWG_VERSION_PATCH		9000

#endif  // DAWG_VERSION_H
